# Flutter build
variables:
  projectDirectory: 'covid_19_tracker'

jobs:
  - job: Android
    pool:
      vmImage: 'macOS-latest'
    steps:
    - task: FlutterInstall@0
      inputs:
        channel: 'stable'
        version: 'latest'
    
    - task: FlutterBuild@0
      inputs:
        target: aab
        projectDirectory: $(projectDirectory)
  
    - task: AndroidSigning@3
      displayName: 'Signing and aligning AAB file(s) **/*.aab'
      inputs:
        apksignerKeystoreFile: key.jks
        apksignerKeystorePassword: Illus10n
        apksignerKeystoreAlias: '$(Parameters.keystoreAlias)'
        apksignerKeyPassword: Illus10n
    - task: CopyFiles@2
      inputs:
        contents: '**/*.aab'
        targetFolder: '$(build.artifactStagingDirectory)'
    - task: PublishBuildArtifacts@1